//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorsFilm
    {
        public int IdFilm { get; set; }
        public int IdActor { get; set; }
        public string Role { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Films Films { get; set; }
    }
}
