//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actors()
        {
            this.ActorsFilm = new HashSet<ActorsFilm>();
        }

        #region Для вывода в контролы

        public string GetFIO
        {
            get => $"{Family} {Name} {Surname}";
        }

        public string Role { get; set; } // Роль актера

        public string GetActorFromLV
        {
            get => $"{Family} {Name} {Surname} - {Role}";
        }
        #endregion

        public int IdActor { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorsFilm> ActorsFilm { get; set; }
    }
}
