//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Films()
        {
            this.ActorsFilm = new HashSet<ActorsFilm>();
            this.Ratings = new HashSet<Ratings>();
        }
    
        // Для вывода в контролах
        public string producer_fio { get; set; }
        public string Genre { get; set; }
        public string date
        {
            get
            {
                return $"{Year.Year}";
            }
        }

        public int IdFilm { get; set; }
        public string Name { get; set; }
        public int IdProducer { get; set; }
        public System.DateTime Year { get; set; }
        public int IdGenre { get; set; }
        public Nullable<int> Rating { get; set; }
        public byte[] Poster { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorsFilm> ActorsFilm { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Producers Producers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}
