//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int IdRating { get; set; }
        public int IdFilm { get; set; }
        public int IdUser { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Users Users { get; set; }
    }
}
